### ISSUE TITLE
Ignore outside clicks on certain elements?

### ISSUE THREAD

**Issue by cssagogo** [ndelvalle/v-click-outside#129]
Is there a way to ignore clicks from outside elements similar to what is described in this article?

https://tahazsh.com/detect-outside-click-in-vue

The use case would be a button on the page that reveals some panel.  Clicking the button again will handle closing the panel so the outside click handling is not needed on it.

**Comment by insanealec** [comment]
What I've done is check for the target within the `onClickOutside` method. Since the event comes in as the first parameter, I check the `event.target.classList` for a specific class that I don't want to trigger what `onClickOutside` does. If the classList has the class that I'm excluding, I just skip doing the event.

Here's an example:
```
onClickOutside(event, el) {
   //I use Lodash here, but you can search the classList yourself, or check the ID or other attributes of the element clicked on.
   const isToggler = _.findIndex(event.target.classList, (c) => {
      return c == 'dropdown-toggler';
   }) != -1;
   if (!isToggler) {
      closeDropdown();
   }
}
```

I hope this helps!

**Comment by ndelvalle** [comment]
@cssagogo does insanealec answer work for you? Using the middleware option is another cleaner approach that you can use, check the middleware usage example [here](https://github.com/ndelvalle/v-click-outside#use) Let me know if this helps.
