### ISSUE TITLE
detectIframe default

### ISSUE THREAD

**Issue by 719media** [ndelvalle/v-click-outside#232]
I really feel detectIframe should have been default false instead of default true
I guess it's probably too late to change this behavior, but it caused me quite a few problems when using a paypal button in a drawer, as the paypal button is an iframe, so my drawer was having a v-click-outside behavior causing it to close instead of allowing the customer to continue down the paypal flow.

I figure I would at least mention it as reason to have the default be false.

The same problem would happen to anyone who is using iframe stuff, like facebook like icons, payment processing entry, etc.

**Comment by ndelvalle** [comment]
@719media yep, totally agree, my fault 😇. Thanks for creating the issue.

**Comment by renatodeleao** [comment]
@719media i've coded the feature ✋  Sry for the trouble and thanks for reporting the issue! Making it `false` by default would have been the wisest move!

Looking at the bright side, now I can see room for improvement 💪 

thinking out-loud we can make iframe detection a little bit smarter: instead of blindly checking `document.activeElement.tagName === 'IFRAME'` we should check if that particular `iframe` is inside `v-click-outside` `element` and prevent the `handler` execution! 

https://github.com/ndelvalle/v-click-outside/blob/75c23d40c18726646caf5affcd4aae7f51aa7dbe/src/v-click-outside.js#L33-L42

Pseudo-code
```js
function onFauxIframeClick({ el, event, handler, middleware }) { 
   // Note: on firefox clicking on iframe triggers blur, but only on 
   //       next event loop it becomes document.activeElement 
   // https://stackoverflow.com/q/2381336#comment61192398_23231136 
   setTimeout(() => { 
     const { activeElement } = document

     if (activeElement.tagName === 'IFRAME' && !el.contains(activeElement)) { 
       execHandler({ event, handler, middleware }) 
     } 
   }, 0) 
}

```

What do you guys think? cc: @ndelvalle
