### ISSUE TITLE
Support for inline expressions

### ISSUE THREAD

**Issue by Danktuary** [ndelvalle/v-click-outside#34]
Support for inline expressions would be neat. Instead of doing all this:

```vue
<template>
	<button @click="showStuff = !showStuff" v-click-outside="hideStuff">
		Settings
	</button>
</template>

<script>
export default {
	// ...
	methods: {
		hideStuff() {
			this.showStuff = false;
		},
	},
};
</script>
```

It could be simplified to this:
```vue
<template>
	<a href="#" @click.prevent="showMenu = !showMenu" v-click-outside="showMenu = false">
		Settings
	</a>
</template>
```

Of course, that probably isn't the only use-case, but just the first one that comes to mind. 😄

**Comment by ndelvalle** [comment]
Hi, @Danktuary indeed this could simplify things, sorry for the delay in answering this. I think this can be solved using the binding expression.
Do you mind trying to implement it 🙂I can give you a hand if you want, otherwise, I will make some time to do it.

**Comment by Danktuary** [comment]
Sure, I don't mind giving it a shot! No promises though because I don't have much experience with Vue directive dev. 😅 But I'll give it a go in the next couple days.

**Comment by drank** [comment]
@ndelvalle , is there any development in this direction?

**Comment by ndelvalle** [comment]
@drank not at the moment 😔. Any help would be appriciated 👍

**Comment by ndelvalle** [comment]
@monkeyWzr I see. I thought this was going to be possible without the arrow function, but apparently not.

About the arrow function usage:
If we save the arrow function in a variable we can still remove the event listener, for example:

```js
const func = (arg) => console.log(arg)

// Add event listener
document.addEventListener('keyup', func)

// Remove event listener
document.removeEventListener('keyup', func)
```

**Comment by monkeyWzr** [comment]
@ndelvalle Thanks a lot!

**Comment by monkeyWzr** [comment]
@ndelvalle Sorry I was focusing on the wrong point. The reason the `removeEventListener` doesn't work is not about arrow functions (because they are already been wrapped up and saved in the global `directive` variable), it's about the `setTimeout` instead.

The current code for binding [https://github.com/ndelvalle/v-click-outside/blob/c59e1d3fc3a76dc66ca21225355ac3e29d48352d/lib/v-click-outside.js#L74](https://github.com/ndelvalle/v-click-outside/blob/c59e1d3fc3a76dc66ca21225355ac3e29d48352d/lib/v-click-outside.js#L74)

somehow makes `removeEventListener` work unexpectly. After I change it to 
```javascript
setTimeout(() => document.addEventListener(event, handler), 0)
```
`removeEventListener` works as we want.

Please check the PR #69 (including test cases updates). Thank you very much!
