### ISSUE TITLE
Multiple event on touch device.

### ISSUE THREAD

**Issue by mrleblanc101** [ndelvalle/v-click-outside#90]
Event is called on TouchStart and on Click.
It should only be called on one or the other.
Since there is no global plugin config, I need to create a config object every time I use the directive just to redefine the events instead of using the function syntax.
The bug seems to come from #44 2 months ago

**Comment by mrleblanc101** [comment]
My issue is that I toggle something on click-outside.
On desktop the function is called once and it toggle. If I put Chrome in touch simulator or if I use xcode simulator, the function is called twice (touchstart and click).

**Comment by ndelvalle** [comment]
Sorry for the late respose @mrleblanc101. So, when you do a click on xcode simulator, the event click `touchstart` and `click` are fired? I thought just `touchstart` would be executed. Do you think that removing the `click` event from the default [here](https://github.com/ndelvalle/v-click-outside/blob/master/lib/v-click-outside.js#L5) would work for you and in general cases?

About the configuration, I agree it would be nice to have a global configuration that we can set. Do you have a bit of time to implement it? Otherwise, I can implement it in the future.

**Comment by phof** [comment]
@ndelvalle FYI removing the `click` event form the line you indicated resolves the issue for me.

**Comment by aariacarterweir** [comment]
Have created a PR to address the issue, the problem I found is that touch devices (eg: iOS Safari) emit both a touchstart and click event when the user taps on something like a button etc.

What's really cooked is that this double firing of events happens to buttons tapped within the element that has the directive on it and for some reason triggers the associated handler to fire. This means if you have v-clickoutside on an element and then you tap a button inside it, the handler will fire incorrectly.

This all seems to be fixed by just removing the extra click event for touch devices.

**Comment by aariacarterweir** [comment]
Actually..... found that the same problem was happening on desktop too. Had to change the desktop event to "mousedown" in order to fix this, there might be something else going on here....

**Comment by aariacarterweir** [comment]
Alrighty - figured this out. When one clicks or interacts with an element within the directive target and that element is v-if'd out of the dom, by the time `el.contains` runs the clicked element is no longer within the directive target and `el.contains` returns false... This is a different bug altogether, I will update my PR to just include a fix for this issue and start another issue for this other error at some point

**Comment by mrleblanc101** [comment]
Hi,
After further investigation, I don't think we should use TouchStart event on mobile device.
TouchStart (just like MouseDown) should never be used for these sort of interaction as they are not cancellable. Also TouchStart is triggered sooner relative to click (**TouchStart**, TouchMove, TouchEnd VS. MouseDown, MouseUp, **Click**)
Considering the given order in which events are processed, we should always use click event on desktop and touchend on mobile device. Or use click on both desktop and mobile device as TouchStart + TouchEnd will always trigger a click event.

1. touchstart
2. touchmove
3. touchend
4. mouseover
5. mousemove
6. mousedown
7. mouseup
8. click

**Comment by mrleblanc101** [comment]
As a workaround, i added `if (event.type === 'touchstart') return false;` to my function
